using TestsGeneratorLibrary;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using NUnit.Framework;
using Moq;

namespace TestsGeneratorTests
{
    public class TestsGeneratorTests
    {
        [SetUp]
        public void Setup()
        {

        }

        [Test]
        public void GenerateTestsUnitTest()
        {
            string sourceCode = "";
            Task<TestUnit[]> actual = TestsGenerator.GenerateTests(sourceCode);
            Task<TestUnit[]> expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}